name: piggywise_simulator
description: "A piggy simulator for Piggywise project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  agattp:
    git:
      url: git@github.com:anlix-io/agattp.git

  cupertino_icons: ^1.0.8

  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/piggy.svg
    - assets/cash.mp3
